///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GitTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("61ac5756-b44b-4a5c-b88c-9a277bbc6bb0")]
    public partial class GitTestsRepository : RepoGenBaseFolder
    {
        static GitTestsRepository instance = new GitTestsRepository();
        GitTestsRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the GitTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("61ac5756-b44b-4a5c-b88c-9a277bbc6bb0")]
        public static GitTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitTestsRepository() 
            : base("GitTestsRepository", "/", null, 0, false, "61ac5756-b44b-4a5c-b88c-9a277bbc6bb0", ".\\RepositoryImages\\GitTestsRepository61ac5756.rximgres")
        {
            _applicationundertest = new GitTestsRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("61ac5756-b44b-4a5c-b88c-9a277bbc6bb0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("68069c15-dbde-40a8-b599-f6d9492db5c5")]
        public virtual GitTestsRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GitTestsRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("68069c15-dbde-40a8-b599-f6d9492db5c5")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            GitTestsRepositoryFolders.ContentFolder _content;
            RepoItemInfo _lbl_yourstoreInfo;
            RepoItemInfo _cbo_currencyInfo;
            RepoItemInfo _btn_usdollarInfo;
            RepoItemInfo _btn_cartInfo;
            RepoItemInfo _msg_successaddedInfo;
            RepoItemInfo _lnk_carttotalInfo;
            RepoItemInfo _strongtagcheckoutInfo;
            RepoItemInfo _lnk_checkoutInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='demo.opencart.com']", parentFolder, 30000, null, false, "68069c15-dbde-40a8-b599-f6d9492db5c5", "")
            {
                _content = new GitTestsRepositoryFolders.ContentFolder(this);
                _lbl_yourstoreInfo = new RepoItemInfo(this, "lbl_YourStore", ".//div[#'logo']//a[@innertext='Your Store']", 30000, null, "ce62a708-03fe-4211-8645-182efb2cdc98");
                _cbo_currencyInfo = new RepoItemInfo(this, "cbo_Currency", ".//form[#'form-currency']//span[@innertext='Currency']", 30000, null, "937a78d5-fad4-4b84-a4e3-de1eaed764a4");
                _btn_usdollarInfo = new RepoItemInfo(this, "btn_USDollar", ".//form[#'form-currency']//button[@innertext='$ US Dollar']", 30000, null, "d9a1f4bb-e455-49bb-bfe4-e04a87edc48f");
                _btn_cartInfo = new RepoItemInfo(this, "btn_Cart", ".//button[#'button-cart']", 30000, null, "cf781813-8767-4d15-a987-52b035ee2beb");
                _msg_successaddedInfo = new RepoItemInfo(this, "msg_SuccessAdded", ".//div[#'product-product']/div[@innertext>'Success: You have added  to']", 30000, null, "59e638a2-1abb-4b7b-a71e-29dd75a0bc23");
                _lnk_carttotalInfo = new RepoItemInfo(this, "lnk_CartTotal", ".//span[#'cart-total']", 30000, null, "23f26f8d-9f0e-4b35-ae86-61ba42ae9db8");
                _strongtagcheckoutInfo = new RepoItemInfo(this, "StrongTagCheckout", ".//div[#'cart']//strong[@innertext=' Checkout']", 30000, null, "8968e7f2-6cbf-4c0d-b6f6-ecc4b6e49a42");
                _lnk_checkoutInfo = new RepoItemInfo(this, "lnk_Checkout", ".//div[#'top-links']//span[@innertext='Checkout']", 30000, null, "e01b5452-8961-40e6-bb2c-74397dee8ee9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68069c15-dbde-40a8-b599-f6d9492db5c5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68069c15-dbde-40a8-b599-f6d9492db5c5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lbl_YourStore item.
            /// </summary>
            [RepositoryItem("ce62a708-03fe-4211-8645-182efb2cdc98")]
            public virtual Ranorex.ATag lbl_YourStore
            {
                get
                {
                    return _lbl_yourstoreInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lbl_YourStore item info.
            /// </summary>
            [RepositoryItemInfo("ce62a708-03fe-4211-8645-182efb2cdc98")]
            public virtual RepoItemInfo lbl_YourStoreInfo
            {
                get
                {
                    return _lbl_yourstoreInfo;
                }
            }

            /// <summary>
            /// The cbo_Currency item.
            /// </summary>
            [RepositoryItem("937a78d5-fad4-4b84-a4e3-de1eaed764a4")]
            public virtual Ranorex.SpanTag cbo_Currency
            {
                get
                {
                    return _cbo_currencyInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The cbo_Currency item info.
            /// </summary>
            [RepositoryItemInfo("937a78d5-fad4-4b84-a4e3-de1eaed764a4")]
            public virtual RepoItemInfo cbo_CurrencyInfo
            {
                get
                {
                    return _cbo_currencyInfo;
                }
            }

            /// <summary>
            /// The btn_USDollar item.
            /// </summary>
            [RepositoryItem("d9a1f4bb-e455-49bb-bfe4-e04a87edc48f")]
            public virtual Ranorex.ButtonTag btn_USDollar
            {
                get
                {
                    return _btn_usdollarInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btn_USDollar item info.
            /// </summary>
            [RepositoryItemInfo("d9a1f4bb-e455-49bb-bfe4-e04a87edc48f")]
            public virtual RepoItemInfo btn_USDollarInfo
            {
                get
                {
                    return _btn_usdollarInfo;
                }
            }

            /// <summary>
            /// The btn_Cart item.
            /// </summary>
            [RepositoryItem("cf781813-8767-4d15-a987-52b035ee2beb")]
            public virtual Ranorex.ButtonTag btn_Cart
            {
                get
                {
                    return _btn_cartInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btn_Cart item info.
            /// </summary>
            [RepositoryItemInfo("cf781813-8767-4d15-a987-52b035ee2beb")]
            public virtual RepoItemInfo btn_CartInfo
            {
                get
                {
                    return _btn_cartInfo;
                }
            }

            /// <summary>
            /// The msg_SuccessAdded item.
            /// </summary>
            [RepositoryItem("59e638a2-1abb-4b7b-a71e-29dd75a0bc23")]
            public virtual Ranorex.DivTag msg_SuccessAdded
            {
                get
                {
                    return _msg_successaddedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The msg_SuccessAdded item info.
            /// </summary>
            [RepositoryItemInfo("59e638a2-1abb-4b7b-a71e-29dd75a0bc23")]
            public virtual RepoItemInfo msg_SuccessAddedInfo
            {
                get
                {
                    return _msg_successaddedInfo;
                }
            }

            /// <summary>
            /// The lnk_CartTotal item.
            /// </summary>
            [RepositoryItem("23f26f8d-9f0e-4b35-ae86-61ba42ae9db8")]
            public virtual Ranorex.SpanTag lnk_CartTotal
            {
                get
                {
                    return _lnk_carttotalInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lnk_CartTotal item info.
            /// </summary>
            [RepositoryItemInfo("23f26f8d-9f0e-4b35-ae86-61ba42ae9db8")]
            public virtual RepoItemInfo lnk_CartTotalInfo
            {
                get
                {
                    return _lnk_carttotalInfo;
                }
            }

            /// <summary>
            /// The StrongTagCheckout item.
            /// </summary>
            [RepositoryItem("8968e7f2-6cbf-4c0d-b6f6-ecc4b6e49a42")]
            public virtual Ranorex.StrongTag StrongTagCheckout
            {
                get
                {
                    return _strongtagcheckoutInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The StrongTagCheckout item info.
            /// </summary>
            [RepositoryItemInfo("8968e7f2-6cbf-4c0d-b6f6-ecc4b6e49a42")]
            public virtual RepoItemInfo StrongTagCheckoutInfo
            {
                get
                {
                    return _strongtagcheckoutInfo;
                }
            }

            /// <summary>
            /// The lnk_Checkout item.
            /// </summary>
            [RepositoryItem("e01b5452-8961-40e6-bb2c-74397dee8ee9")]
            public virtual Ranorex.SpanTag lnk_Checkout
            {
                get
                {
                    return _lnk_checkoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lnk_Checkout item info.
            /// </summary>
            [RepositoryItemInfo("e01b5452-8961-40e6-bb2c-74397dee8ee9")]
            public virtual RepoItemInfo lnk_CheckoutInfo
            {
                get
                {
                    return _lnk_checkoutInfo;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("0ae983a3-a007-48b4-a6a2-b27a661b9a98")]
            public virtual GitTestsRepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("0ae983a3-a007-48b4-a6a2-b27a661b9a98")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_checkoutInfo;
            RepoItemInfo _lnk_macbookInfo;
            RepoItemInfo _lbl_precioInfo;
            RepoItemInfo _lbl_shoppingcart1000kgInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", ".//div[#'content']", parentFolder, 30000, null, false, "0ae983a3-a007-48b4-a6a2-b27a661b9a98", "")
            {
                _btn_checkoutInfo = new RepoItemInfo(this, "btn_Checkout", ".//a[@innertext='Checkout']", 30000, null, "7d517cd0-2b9c-4e45-91f8-2a0644d1e5e3");
                _lnk_macbookInfo = new RepoItemInfo(this, "lnk_MacBook", ".//a[@innertext='MacBook']", 30000, null, "2288231b-5d59-4420-a9ea-b2fdc1ebe127");
                _lbl_precioInfo = new RepoItemInfo(this, "lbl_Precio", ".//h2[@innertext='$602.00']", 30000, null, "cca714b0-829c-4e19-b693-6be3fdba7fe1");
                _lbl_shoppingcart1000kgInfo = new RepoItemInfo(this, "lbl_ShoppingCart1000kg", "h1[@innertext~'Shopping Cart']", 30000, null, "9259bb08-2344-4747-815a-d67371f3e67a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ae983a3-a007-48b4-a6a2-b27a661b9a98")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ae983a3-a007-48b4-a6a2-b27a661b9a98")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_Checkout item.
            /// </summary>
            [RepositoryItem("7d517cd0-2b9c-4e45-91f8-2a0644d1e5e3")]
            public virtual Ranorex.ATag btn_Checkout
            {
                get
                {
                    return _btn_checkoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btn_Checkout item info.
            /// </summary>
            [RepositoryItemInfo("7d517cd0-2b9c-4e45-91f8-2a0644d1e5e3")]
            public virtual RepoItemInfo btn_CheckoutInfo
            {
                get
                {
                    return _btn_checkoutInfo;
                }
            }

            /// <summary>
            /// The lnk_MacBook item.
            /// </summary>
            [RepositoryItem("2288231b-5d59-4420-a9ea-b2fdc1ebe127")]
            public virtual Ranorex.ATag lnk_MacBook
            {
                get
                {
                    return _lnk_macbookInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lnk_MacBook item info.
            /// </summary>
            [RepositoryItemInfo("2288231b-5d59-4420-a9ea-b2fdc1ebe127")]
            public virtual RepoItemInfo lnk_MacBookInfo
            {
                get
                {
                    return _lnk_macbookInfo;
                }
            }

            /// <summary>
            /// The lbl_Precio item.
            /// </summary>
            [RepositoryItem("cca714b0-829c-4e19-b693-6be3fdba7fe1")]
            public virtual Ranorex.H2Tag lbl_Precio
            {
                get
                {
                    return _lbl_precioInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The lbl_Precio item info.
            /// </summary>
            [RepositoryItemInfo("cca714b0-829c-4e19-b693-6be3fdba7fe1")]
            public virtual RepoItemInfo lbl_PrecioInfo
            {
                get
                {
                    return _lbl_precioInfo;
                }
            }

            /// <summary>
            /// The lbl_ShoppingCart1000kg item.
            /// </summary>
            [RepositoryItem("9259bb08-2344-4747-815a-d67371f3e67a")]
            public virtual Ranorex.H1Tag lbl_ShoppingCart1000kg
            {
                get
                {
                    return _lbl_shoppingcart1000kgInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The lbl_ShoppingCart1000kg item info.
            /// </summary>
            [RepositoryItemInfo("9259bb08-2344-4747-815a-d67371f3e67a")]
            public virtual RepoItemInfo lbl_ShoppingCart1000kgInfo
            {
                get
                {
                    return _lbl_shoppingcart1000kgInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
