///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GitTests.Actions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckOut recording.
    /// </summary>
    [TestModule("ba284c26-30ba-4ea1-82e4-7d88229ff31a", ModuleType.Recording, 1)]
    public partial class CheckOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GitTests.GitTestsRepository repository.
        /// </summary>
        public static global::GitTests.GitTestsRepository repo = global::GitTests.GitTestsRepository.Instance;

        static CheckOut instance = new CheckOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // ===== Check Out ====
            Report.Log(ReportLevel.Info, "Section", "===== Check Out ====", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.lnk_Checkout' at Center.", repo.ApplicationUnderTest.lnk_CheckoutInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.lnk_Checkout.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.lnk_Checkout'", repo.ApplicationUnderTest.lnk_CheckoutInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.ApplicationUnderTest.lnk_CheckoutInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
