///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GitTests.Actions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetCurrency recording.
    /// </summary>
    [TestModule("1c075077-f626-4f4c-a942-6e82b56c31ea", ModuleType.Recording, 1)]
    public partial class SetCurrency : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GitTests.GitTestsRepository repository.
        /// </summary>
        public static global::GitTests.GitTestsRepository repo = global::GitTests.GitTestsRepository.Instance;

        static SetCurrency instance = new SetCurrency();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetCurrency()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetCurrency Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // ===== Set Currency =====
            Report.Log(ReportLevel.Info, "Section", "===== Set Currency =====", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.cbo_Currency' at 40;11.", repo.ApplicationUnderTest.cbo_CurrencyInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.cbo_Currency.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.btn_USDollar' at 31;10.", repo.ApplicationUnderTest.btn_USDollarInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.btn_USDollar.Click("31;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
